#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Mar 23 22:00:39 IST 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_gen_behav -key {Behavioral:sim_1:Functional:tb_gen} -tclbatch tb_gen.tcl -view /home/dell/Desktop/IIITB/8thSem/ASICproj/LDPC_ASIC/vivado_proj/tb_gen_behav.wcfg -log simulate.log"
xsim tb_gen_behav -key {Behavioral:sim_1:Functional:tb_gen} -tclbatch tb_gen.tcl -view /home/dell/Desktop/IIITB/8thSem/ASICproj/LDPC_ASIC/vivado_proj/tb_gen_behav.wcfg -log simulate.log

