#################################################################################
# PHASE 1: INITIALIZATION, CONFIGURATION, AND GLOBAL SETTINGS
#################################################################################

# Load design-specific environment variables (e.g., $tech_node, $hdl_file, $utilization)
source ./scripts_user/config_script.tcl

# Configure multi-threading: Utilize the maximum available CPU cores on the local machine
setMultiCpuUsage -localCpu max

# Enable specific latch-recognition modeling rules within the internal timing engine
set ::TimeLib::tsgMarkCellLatchConstructFlag 1

# Initialize Quantus QRC parasitic extraction configuration/library file variables as empty
set conf_qxconf_file {NULL}
set conf_qxlib_file {NULL}

# Allow the Clock Tree Synthesis (CTS) engine to see and manage both Multi-Mode Multi-Corner views
set dbgDualViewAwareXTree 1

# Define the forward slash '/' as the hierarchy delimiter when writing or reading files (like DEF)
set defHierChar {/}

# Enable echoing of messages from distributed clients to the master terminal
set distributed_client_message_echo {1}

# Prevent automatic redirection of MMMC timing reports away from default log directories
set distributed_mmmc_disable_reports_auto_redirection {0}

# Enable Interface Logic Model (ILM) dual-view graphical rendering for FAST (ILM) timing analyses
set enable_ilm_dual_view_gui_and_attribute 1

# Reset and clean command option histories when printing tool mode parameters
set enc_enable_print_mode_command_reset_options 1

# Specify that the incoming gate-level netlist is in Verilog format
set init_design_netlisttype verilog

# Define the path to the synthesis-optimized gate-level netlist generated by Cadence Genus
set init_verilog "./genus/synthesis/$hdl_file/$tech_node/opt/${hdl_file}_syn_opt.v"

# Disable automatic top-module deduction; the top-level cell must be explicitly defined
set init_design_settop 0

# Set parasitic extraction (RC) nominal resistance scaling factors to 1.0 (no scaling)
set pegDefaultResScaleFactor 1
set pegDetailResScaleFactor 1

# Enable Quantus QRC to extract and manage parasitic corners under dual MMMC views
set pegEnableDualViewForTQuantus 1

# Standardize the column formatting for reporting disabled or inactive timing arcs
set report_inactive_arcs_format {from to when arc_type sense reason}

# Control how Interface Logic Models (ILMs) are unflattened during placement legality checks
set spgUnflattenIlmInCheckPlace 2

# Throw a strict fatal error if a port pin name in the netlist mismatches the physical LEF file
set init_verilog_tolerate_port_mismatch 0

# Allow the tool to load netlists referencing cells not explicitly declared in the timing library
set load_netlist_ignore_undefined_cell 1

# Declare the global net name used for Power
set init_pwr_net {VDD}

# Declare the global net name used for Ground
set init_gnd_net {VSS}

# Configure latch timing paths to use the maximum possible time-borrowing duration
set latch_time_borrow_mode max_borrow

# Set the path to both physical technology LEFs (metal layers, vias) and macro LEFs (standard cells)
set init_lef_file "./pdks/$tech_node/lef/*tech.lef ./pdks/$tech_node/lef/*macro.lef"


#################################################################################
# PHASE 2: MULTI-MODE MULTI-CORNER (MMMC) SETUP & DESIGN INGESTION
#################################################################################

# Create an RC Corner combining the captable and QRC tech files to accurately model wire parasitics
create_rc_corner -name rc_corner \
  -cap_table "./pdks/$tech_node/captable/cln28hpl_1p10m+alrdl_5x2yu2yz_typical.capTbl" \
  -preRoute_res {1.0} -preRoute_cap {1.0} -preRoute_clkres {0.0} -preRoute_clkcap {0.0} \
  -postRoute_res {1.0} -postRoute_cap {1.0} -postRoute_xcap {1.0} -postRoute_clkres {0.0} -postRoute_clkcap {0.0} \
  -qx_tech_file "./pdks/$tech_node/qrc/${qrc_file}.tch"

# Group fast cell models for best-case/hold timing analysis
create_library_set -name fast -timing "./pdks/$tech_node/lib/$fast_cell_type"

# Group slow cell models for worst-case/setup timing analysis
create_library_set -name slow -timing "./pdks/$tech_node/lib/$slow_cell_type"

# Load the Synopsys Design Constraints (SDC) file defining clocks and design constraints
create_constraint_mode -name constraints -sdc_files "./genus/synthesis/$hdl_file/$tech_node/opt/${hdl_file}_syn_opt.sdc"

# Associate fast libraries with the RC corner to analyze fastest signal propagation speeds
create_delay_corner -name fast_delay -library_set {fast} -rc_corner {rc_corner}

# Associate slow libraries with the RC corner to analyze slowest signal propagation speeds
create_delay_corner -name slow_delay -library_set {slow} -rc_corner {rc_corner}

# Set up worst-case scenario analysis view (slow cells, long wire delays, standard SDC)
create_analysis_view -name setup_analysis -constraint_mode {constraints} -delay_corner {slow_delay}

# Set up best-case scenario analysis view (fast cells, short wire delays, standard SDC)
create_analysis_view -name hold_analysis -constraint_mode {constraints} -delay_corner {fast_delay}

# Ingest the netlist and physical views using the established setup and hold views
init_design -setup {setup_analysis} -hold {hold_analysis}

# Commit and activate the MMMC analysis views in the session
set_analysis_view -setup {setup_analysis} -hold {hold_analysis}

# Connect VDD power pins of the cells to the global VDD netlist net
globalNetConnect VDD -type pgpin -pin VDD -override -verbose -netlistOverride

# Connect VSS ground pins of the cells to the global VSS netlist net
globalNetConnect VSS -type pgpin -pin VSS -override -verbose -netlistOverride


#################################################################################
# PHASE 3: FLOORPLANNING & POWER PLANNING
#################################################################################

# Configure floorplan to initialize all legal standard cell site rows in core area
setFPlanMode -initAllCompatibleCoreSiteRows true

# Define core size, aspect ratio, utilization density, and outer I/O boundary margins
floorPlan -coreMarginsBy io -site CoreSite -r "$aspect_ratio_core" "$utilization" "$lmargin" "$bmargin" "$rmargin" "$tmargin"

# Save the unplaced floorplan representation as a DEF file
defOut -floorplan -netlist -unplaced "./innovus/$hdl_file/$tech_node/def/floorplan.def"

# Set up via generation parameters to stack from bottom row metal (M1) up to ring metal (M11)
setAddRingMode -stacked_via_top_layer M11 -stacked_via_bottom_layer M1 

# Synthesize the main VDD/VSS power ring around the core using top metals M10 & M11
addRing -nets {VDD VSS} -type core_rings -around user_defined -center 0 -spacing 0.5 -width 0.5 -offset 0.5 -threshold auto -layer {top M11 bottom M11 right M10 left M10}

# Lay down vertical power stripes on metal M10 to distribute power evenly across the block
addStripe -nets {VDD VSS} -layer M10 -width 0.5 -spacing 1 -number_of_sets 1 -start_from left

# Perform special routing to physically hook cell rows (M1 rails) to stripes and rings
sroute -connect {blockPin padPin padRing corePin floatingStripe } -allowJogging true -allowLayerChange true -blockPin useLef -targetviaLayerRange {M1 M10}


#################################################################################
# PHASE 4: PLACEMENT & PRE-CTS OPTIMIZATION
#################################################################################

# Set placement tool engine to respect block floorplan boundaries
setPlaceMode -place_design_floorplan_mode true

# Set optimization intensity high for congestion/timing and allow scan-chain reordering
setPlaceMode -place_global_timing_effort high -place_global_cong_effort high -place_global_reorder_scan true 

# Execute placement and output the intermediate run reports
place_opt_design -out_dir "./innovus/$hdl_file/$tech_node/optimization_reports/placement/"

# Perform the final physical legalizing placement of all standard cells in the site rows
place_design

# Enable signal-integrity (SI) crosstalk awareness during delay calculations
setDelayCalMode -SIAWare true

# Perform optimization to repair setup violations before building physical clock trees (Pre-CTS)
optDesign -preCTS -outDir "./innovus/$hdl_file/$tech_node/optimization_reports/preCTS/"

# Generate initial timing reports assuming ideal clock distribution networks
timeDesign -preCTS -outDir "./innovus/$hdl_file/$tech_node/timing/prects/"

# Write the placed database out into a DEF file
defOut -floorplan -netlist "./innovus/$hdl_file/$tech_node/def/placement.def"


#################################################################################
# PHASE 5: CUSTOM BALANCED I/O PIN DISTRIBUTION
#################################################################################

# Extract all signal port names from the database, filtering out any clock-related ports
set all_ports       [dbGet top.terms.name -v *clk*]

# Determine the total quantity of I/O signal ports
set num_ports       [llength $all_ports]

# Find the threshold division index to divide ports into 4 equal sets
set quarter_ports_idx [expr $num_ports / 4]

# Slice the port list into four distinct spatial groups for the physical chip edges
set pins_top        [lrange $all_ports 0                               $quarter_ports_idx-1]
set pins_bottom     [lrange $all_ports $quarter_ports_idx  [expr $quarter_ports_idx * 2 - 1]]
set pins_left       [lrange $all_ports [expr $quarter_ports_idx * 2] [expr $quarter_ports_idx * 3 - 1]]
set pins_right      [lrange $all_ports [expr $quarter_ports_idx * 3] [expr $num_ports - 1]]

# Retrieve all explicit clock port names
set clock_ports     [dbGet top.terms.name *clk*]
set half_left_idx   [expr [llength $pins_left] / 2]
set half_right_idx  [expr [llength $pins_right] / 2]

# If clock ports exist, loop and distribute them round-robin across all 4 chip boundaries
if { $clock_ports != 0 } {
  foreach port $clock_ports {
    lappend pins_top    [lindex $clock_ports 0]
    lappend pins_bottom [lindex $clock_ports 1]
    lappend pins_left   [lindex $clock_ports 2]
    lappend pins_right  [lindex $clock_ports 3]
  }
}

# Assign the target physical layer (Metal 1) for placing pin access interfaces
set ports_layer M1

# Physically lock and spread the four groups of pins to their assigned chip sides
editPin -layer $ports_layer -pin $pins_top    -side TOP    -spreadType SIDE
editPin -layer $ports_layer -pin $pins_bottom -side BOTTOM -spreadType SIDE
editPin -layer $ports_layer -pin $pins_left   -side LEFT   -spreadType SIDE
editPin -layer $ports_layer -pin $pins_right  -side RIGHT  -spreadType SIDE

# Save the pin-placed floorplan database state to a DEF file
defOut -floorplan -netlist "./innovus/$hdl_file/$tech_node/def/pin_placement.def"


#################################################################################
# PHASE 7: CLOCK TREE SYNTHESIS (CTS)
#################################################################################

# Initialize empty list to hold valid library clock buffer names
set clkbuf_cells {}

# Open raw .lib file in read-only mode to find clock buffer names
set file [open "./pdks/$tech_node/lib/$cell_types" r]

# Read through every line of the timing library
while {[gets $file line] != -1} {
    # If the line identifies a clock buffer ("CLKBUF")
    if {[string match "*CLKBUF*" $line]} {
        # Match pattern containing cell name e.g. "cell (CLKBUF_X1)"
        if {[regexp {^\s*cell\s*\(\s*([^\)]+)\s*\)} $line match cell_name]} {
            # Add unique cell to the buffer list if it isn't already inside
            if {[lsearch -exact $clkbuf_cells $cell_name] == -1} {
                lappend clkbuf_cells $cell_name
            }
        }
    }
}
close $file 

# Perform global logical integrity checks prior to clock synthesis
setCheckMode -all true

# Direct optimizer to correct capacitance and transition violations, ignoring fanout
setOptMode -fixCap true -fixTran true -fixFanoutLoad false

# Restrict CTS engine to build tree structures using ONLY the discovered clkbuf cells
set_ccopt_property buffer_cells $clkbuf_cells

# Prevent clock signals from degrading by setting target transition limit strictly to 100ps
set_ccopt_property target_max_trans 0.1 

# Execute Clock Concurrent Optimization (CCOpt) to synthesize clock tree and routes
ccopt_design -outDir "./innovus/$hdl_file/$tech_node/optimization_reports/ccopt_CTS/"

# Perform timing and routing cleanup optimizations on logic with actual clocks (Post-CTS)
optDesign -postCTS -outDir "./innovus/$hdl_file/$tech_node/optimization_reports/postCTS/"

# Generate detailed Post-CTS timing analyses
timeDesign -postCTS -outDir "./innovus/$hdl_file/$tech_node/timing/postCTS/"

# Export the clock-synthesized database state as a DEF file
defOut -floorplan -netlist "./innovus/$hdl_file/$tech_node/def/cts.def"


#################################################################################
# PHASE 8: DETAILED SIGNAL ROUTING
#################################################################################

# Quiet routing engines and initialize timing parameters
setNanoRouteMode -quiet -timingEngine {}

# Instruct router to construct metal wires while considering timing limits
setNanoRouteMode -quiet -routeWithTimingDriven 1

# Instruct router to consider signal crosstalk (Signal Integrity) when routing
setNanoRouteMode -quiet -routeWithSiDriven 1

# Disable crosstalk repairing loops at initial post-route stages
setNanoRouteMode -quiet -routeWithSiPostRouteFix 0

# Set initial and limit routing iterations to default values
setNanoRouteMode -quiet -drouteStartIteration default
setNanoRouteMode -quiet -routeTopRoutingLayer default
setNanoRouteMode -quiet -routeBottomRoutingLayer default
setNanoRouteMode -quiet -drouteEndIteration default

# Re-enforce Timing-Driven and Crosstalk-Aware routing configs
setNanoRouteMode -quiet -routeWithTimingDriven true
setNanoRouteMode -quiet -routeWithSiDriven true

# Execute full Global and Detailed Routing of signal wires
routeDesign -globalDetail


#################################################################################
# PHASE 9: ROUTING CLEANUP & SKEW OPTIMIZATION
#################################################################################

# Reset end-cap insertion constraints and disable physical boundary tap cells
setEndCapMode -reset    
#EndCap: Dummy std cells at the end of site rows to protect real logic cells from Lithography variation
setEndCapMode -boundary_tap false   
# Well Tap Cell: Ensures trans N-well -> VDD and P-well -> VSS
# Set to FALSE cuz some EndCap celss violate this

# Initialize antenna-effect physical protection layer settings
setNanoRouteMode -quiet -routeAntennaCellName {}

# Configure the tool to utilize "Time borrowing" to fix setup timing on critical nodes
setUsefulSkewMode -maxSkew false -noBoundary false \
  -useCells {dl04d1 bufbd7 buffd2 dl03d1 bufbdf buffda dl02d2 dl03d4 dl04d2 dl02d1 dl01d4 buffd3 bufbda bufbdk buffd4 dl04d4 dl02d4 bufbd4 dl01d2 bufbd3 bufbd1 dl01d1 buffd7 bufbd2 buffd1 dl03d2 inv0d2 invbda inv0da invbdk inv0d1 inv0d7 invbd4 invbd2 inv0d0 invbd7 invbdf inv0d4} \
  -maxAllowedDelay 1
# usecells which aren't P hungry

# Designate specific antenna-diode physical cell names for repair runs
setNanoRouteMode -quiet -routeAntennaCellName adiode

# Set timing-driven routing search effort to high (level 5)
setNanoRouteMode -quiet -routeTdrEffort 5   
# TDR: Time-driven Routing
setNanoRouteMode -quiet -routeTopRoutingLayer default   
setNanoRouteMode -quiet -routeBottomRoutingLayer default
setNanoRouteMode -quiet -drouteEndIteration default
setNanoRouteMode -quiet -routeWithTimingDriven true
setNanoRouteMode -quiet -routeWithSiDriven true

# Rerun signal detail routing while optimizing via selections and spacing out metal wires
routeDesign -globalDetail -viaOpt -wireOpt


#################################################################################
# PHASE 10: POST-ROUTE TIMING OPTIMIZATION & PHYSICAL FINISHING
#################################################################################

# Enable On-Chip-Variation (OCV) analysis to factor in physical manufacturing tolerances
setAnalysisMode -analysisType onChipVariation

# Run timing optimization post-routing, focusing strictly on resolving hold violations
optDesign -postRoute -hold -outDir "./innovus/$hdl_file/$tech_node/optimization_reports/postroute/"

# Dump final routed physical design timing analysis reports
timeDesign -postRoute -outDir "./innovus/$hdl_file/$tech_node/timing/postroute/"

# Define standard physical filler cell list to bridge power rails and logic row wells
set fillercells [list FILL1 FILL2 FILL4 FILL8 FILL16 FILL32 FILL64]

# Configure insertion names and types of standard filler cells
setFillerMode -corePrefix ${hdl_file}_FILL -core ${fillercells}

# Insert fillers across empty gaps, flagging them as locked and fixed in place
addFiller -cell $fillercells -prefix ${hdl_file}_FILL -markFixed 


#################################################################################
# PHASE 11: SIGN-OFF VERIFICATION & FILE PARASITIC EXTRACTION
#################################################################################

# Perform physical Design Rule Checking (DRC) to ensure metal spacing compliance
verify_drc -check_only all -report "./innovus/$hdl_file/$tech_node/${hdl_file}_drc.rpt"

# Verify that there are no shorts or open electrical paths in the physical layout
verifyConnectivity -type all -report "./innovus/$hdl_file/$tech_node/${hdl_file}_connectivity.rpt"

# Export the final fully routed physical layout configuration database as a DEF file
defOut -routing -netlist "./innovus/$hdl_file/$tech_node/def/floorplan.def"

# Extract detailed post-routing physical wire capacitance (RC elements)
extractRC -outfile "./innovus/$hdl_file/$tech_node/parasitics/${hdl_file}.cap"

# Format extracted parasitic wires to standard SPEF format for downstream timing tools
rcOut -spef "./innovus/$hdl_file/$tech_node/parasitics/${hdl_file}.spef"

# Generate Standard Delay Format (SDF) timing file containing cell/interconnect delays
write_sdf "./innovus/$hdl_file/$tech_node/parasitics/${hdl_file}.sdf"

puts "entire process done"


#################################################################################
# PHASE 12: STATISTICAL REPORT GENERATION
#################################################################################

# Write standard structural area, physical footprint, and nested sub-hierarchy area reports
report_area > "./innovus/$hdl_file/$tech_node/reports/${hdl_file}_area.rpt"
report_area -include_physical > "./innovus/$hdl_file/$tech_node/reports/${hdl_file}_area_physical.rpt"
report_area -detail > "./innovus/$hdl_file/$tech_node/reports/${hdl_file}_area_detail.rpt"

# Generate complete and thorough timing path reports
report_timing > "./innovus/$hdl_file/$tech_node/reports/${hdl_file}_timing.rpt"
report_timing -max_paths 1000000000 > "./innovus/$hdl_file/$tech_node/reports/${hdl_file}_timing_all_paths.rpt"

# Generate dynamic and static power dissipation calculations
report_power > "./innovus/$hdl_file/$tech_node/reports/${hdl_file}_power.rpt"

# Write physical metal routing length and via count summaries
report_route > "./innovus/$hdl_file/$tech_node/reports/${hdl_file}_routing_info.txt"

# Establish target directory for routing timing reports
set report_dir "./innovus/$hdl_file/$tech_node/timing_reports/route_reports"

# Verify and create the missing target timing extraction directory
if {![file exists $report_dir]} {
    file mkdir $report_dir
}
file mkdir ./innovus/$hdl_file/$tech_node/timing_reports/route_reports

# Format and isolate timing paths that are experiencing setups/slack violations (slack <= 0)
set_table_style -name report_timing -max_widths {250,50,50,50,50,50} 
report_timing -late -from [all_registers] -to [all_registers] -max_paths 1000000000 -max_slack  0 > "./innovus/$hdl_file/$tech_node/timing_reports/route_reports/timing_route.txt"

puts "label extraction done"